### ISSUE TITLE
Blank 

### ISSUE THREAD

**Issue by bembenk18** [beetlehr/beetlehr#2]
selamat sore, saat saya install di local tampilan hanya blank putih seperti gambar dibawah ini
![image](https://user-images.githubusercontent.com/65327648/213847001-85fef9a6-9e63-4c0e-8718-03aaf36c6ea1.png)

**Comment by bembenk18** [comment]
@ryanaidilp sudah mas, masih sama belum berhasil

**Comment by rizkhal** [comment]
Blank karena components tidak bisa diimport

[Screenshot from 2023-01-26 04-07-47](https://user-images.githubusercontent.com/24653114/214678261-7c0b256a-b3b4-4f1f-a97f-db86d97ea1bf.png)

Saya coba untuk register beberapa global components menggunakan [setup extend](https://github.com/vbenjs/vite-plugin-vue-setup-extend) dan berhasil

[Screenshot from 2023-01-26 04-24-02](https://user-images.githubusercontent.com/24653114/214682425-7eb847c4-962a-4656-88f6-0f96825bee36.png)

[Screenshot from 2023-01-26 04-23-31](https://user-images.githubusercontent.com/24653114/214682478-d333cd09-3163-42bd-a570-8c970ab576bf.png)

[Screenshot from 2023-01-26 04-23-45](https://user-images.githubusercontent.com/24653114/214682831-0034e101-e24c-465b-bbc0-11a19b558b01.png)


Jika ada plan untuk upgrade versi inertia, sepertinya akan bagus kalau sekalian tambahin register global componentnya secara dinamis agar global component ini tidak perlu diimport di setiap page

**Comment by adarmanto** [comment]
Muncul error sama kaya @rizkhal, itu maksudnya perlu edit source codenya berarti ya @rizkhal ?

![image](https://user-images.githubusercontent.com/26041956/214753697-bc77b0c2-45da-4774-b7b2-b84b13e5aee6.png)


```sh
darmanto:beetlehr$ node -v
v18.13.0
darmanto:beetlehr$ yarn -v
1.22.5
darmanto:beetlehr$ npm -v
8.19.3
darmanto:beetlehr$ php -v
PHP 8.2.1 (cli) (built: Jan 13 2023 10:43:08) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.1, Copyright (c), by Zend Technologies
    with Xdebug v3.2.0, Copyright (c) 2002-2022, by Derick Rethans
```

**Comment by rizkhal** [comment]
Iya mas @adarmanto, perlu diedit karena beberapa component tidak bisa diimport.

**Comment by bembenk18** [comment]
file yang perlu diubah yang mana aja ya mas @ryanaidilp ?

**Comment by alansekha** [comment]
Selamat siang teman teman.  Untuk issue ini akhirnya sudah solve 🥳. 

Saya sudah testing di vps juga sudah aman, jadi teman teman bisa coba pull branch terbaru. Lalu bisa coba jalankan yarn build / npm run build.  

Berikut adalah proses testing yang aku lakukan. 
https://www.loom.com/share/117d15e01e1f40f8a66a97d5461ea6b0 

Untuk sementara issue ini aku close dulu, jadi nanti kalau teman teman mengalami kendala lain bisa coba buka issue baru ya. Terima kasih 🙏
